### ISSUE TITLE
footnote placement in rendered manuscript should be left-adjusted

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#116]
in the PDF I have in front of me, the footnotes at end of sentences are not left-flush with the period. this is a minor nit but a nit nonetheless :). is this just a stylesheet issue or ...?

**Comment by slochower** [comment]
Yep, that should be a stylesheet thing (i.e., strictly non-content). We have some other code modifications in place that might take care of this (but haven't checked yet). cc @vincerubinetti

**Comment by dhimmel** [comment]
Is this in reference to the superscript numbers in [Table 1](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#tbl:platforms)?

> ![image](https://user-images.githubusercontent.com/1117703/52305743-dbf0c000-2963-11e9-8022-836cd283e6ba.png)

There are not left-flush because they apply the following sentence (not the previous). It's confusing, and I think the caption probably should not use superscripts (although the table cells should).

> We have some other code modifications in place that might take care of this (but haven't checked yet).

The new default theme, which hasn't yet been ported to this repo, will change the appearance of superscripts hopefully to be better. However, that is not the main issue here IIUC.

**Comment by vincerubinetti** [comment]
If the issue is what the screenshot @dhimmel posted, that is not an issue at all. If you look at the mardown input, those superscripts have a space placed before them, not after them. In other words, those super scripts actually belong to sentence after them, not before them.

**Comment by ctb** [comment]
I've never seen this style of footnotes (prepending rather than postpending). Consider placing at end of sentence, maybe?

**Comment by agitter** [comment]
Now that you point it out, this convention is confusing.  We'll revisit the table and its caption to make this more clear.
