### ISSUE TITLE
"requesting modifications as depicted in 7."

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#117]
the number 7 seems to refer to a citation (at least that's the hover view) but should maybe be in square brackets, i.e. [7]?

**Comment by slochower** [comment]
Yeah, I think you're right.

**Comment by dhimmel** [comment]
Regarding this sentence in [this version](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/):

> GitHub’s review interface allows anyone to comment on the changes, globally or at specific lines, asking questions or requesting modifications as depicted in [7](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#ref-opQBBK06).

This was intentional since the citation is being used as a noun in the sentence. Sometimes this is called an in-text citation and is probably more common when using author style citations like:

> GitHub’s review interface allows anyone to comment on the changes, globally or at specific lines, asking questions or requesting modifications as depicted in [Israeli (2017)](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#ref-opQBBK06).

We'll consider whether to change this. Somewhat related, new Manubot frontend enhancements in the works will provide toolips upon hovering over a citation. This could have helped reduce confusion here.

**Comment by ctb** [comment]
It was unclear if it was a figure or a citation. Suggest longer form if citation.
