### ISSUE TITLE
GitHub/Zenodo integration

### ISSUE THREAD

**Issue by rgieseke** [greenelab/meta-review#13]
GitHub is mentioned quite often in this manuscript, but it might be helpful to point it out that it's not technically tied to this platform.

Another thing worth mentioning might be the simple integration with Zenodo or Figshare to get a permanent archived version and doi for a manuscript version.

**Comment by agitter** [comment]
Thanks, those are good suggestions.

For deep review, we used bioRxiv to obtain a doi for the pdf of a specific version of the manuscript.  [This report](https://github.com/zietzm/Vagelos2017) used FigShare for a manubot-generated manuscript.  A doi of the full repository with Zenodo integration would serve a slightly different purpose and could be worth mentioning too

**Comment by dhimmel** [comment]
> GitHub is mentioned quite often in this manuscript, but it might be helpful to point it out that it's not technically tied to this platform.

Good point. We should mention that switching from GitHub / Travis CI would not be too difficult, should one of these services cease or start charging $$$.

This is a separate issue than Zenodo / Figshare integration. Those both give DOIs to GitHub releases, IIRC. It's good for longterm preservation, but it's not great IMO for giving a DOI to the manuscript, since the DOI won't resolve to a version of the manuscript. The preprint solves this issue, but is missing the directory content. Also Zenodo doesn't back up the git history with its GitHub integration, I don't think. I'm not sure if Figshare does. We probably want an archiving solution that preserves the git history.

**Comment by rgieseke** [comment]
On the Zenodo/Figshare integration: When posting I had thought that the compiled PDF/HTML were in the same branch as the source files, but they are on `gh-pages` and `output` so archiving would not automatically include both sources and output. 

Have you considered using the '/docs' directory for rendered webpage output? It might require one more step to enable the GitHub pages rendering by switching the output branch, but at the moment it's potentially a bit confusing to have an `/output` directory (more or less empty) and an `output` branch.

Another option could be to archive the builds automatically, there is an open issue at Zenodo for including release artifacts: https://github.com/zenodo/zenodo/issues/1235

Otherwise it's pretty cool how close manubot already is to an open journal system.

**Comment by dhimmel** [comment]
> Have you considered using the `/docs` directory for rendered webpage output?

The decision not to include any output in the `master` branch was intentional. Primarily, output in `master` creates a burden on users to build the manuscript locally (or else have an incomplete PR). We could use CI to commit back to master with output, but that can become trigger race conditions (build starts, someone merges a different PR, then build finishes).

> Another option could be to archive the builds automatically

Yeah, I think an automated method for archiving would fit well within the project. Right now if you archived the output directory, you will capture most of the important files (but not the raw source).

> Otherwise it's pretty cool how close manubot already is to an open journal system.

"open journal system"... that's an interesting tagline for the manubot. I like it!

**Comment by agitter** [comment]
#9 added a few lines about GitHub / Travis CI and states that alternatives exist.  Is there anything else we want to add to this manuscript regarding Zenodo, Figshare, or DOI strategies?  If not, we can close this and move the discussion of auto-archiving to manubot-rootstock.  This also relates to our discussion of auto-archiving issues and reviews (greenelab/manubot-rootstock#45).

**Comment by dhimmel** [comment]
> Is there anything else we want to add to this manuscript regarding Zenodo, Figshare, or DOI strategies

I think it'd be premature to recommend Zenodo archiving. It's not an ideal way to mint a DOI as either:

1. the DOI should refer to just the manuscript and redirect to a view of the manuscript
2. the DOI should refer to the entire git contribution history and redirect to some archive

Zenodo is more like 2, but does not preserve the git history. So I'm in favor of closing as solutions may come along, but let's see them before mentioning them.

**Comment by agitter** [comment]
I'm closing this because we don't have any concrete recommendations about DOIs to add to the meta review.

@rgieseke if you'd like to discuss DOI strategies or output file organization, let's continue the discussion at manubot-rootstock.
