### ISSUE TITLE
Front-end figures and text

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/meta-review#168]
I'll put some figures and write-ups on my involvement in the Manubot project in this issue, so people can review theme for inclusion in the Meta Review.

Here's the first one, overviewing the plugins:

![plugins](https://user-images.githubusercontent.com/8326331/54377249-29470800-465b-11e9-81d8-92e38504b73e.jpg)

I'll probably do another figure of just a general screenshot of the theme and plugins together (more of an overview screenshot).

**Comment by slochower** [comment]
This looks really nice. The only thing I think is a little unclear is the "same citation highlighting." I can see what it is, but I wasn't even aware you added that feature. What are you planning to put into the caption?

**Comment by agitter** [comment]
This looks great.  Do we plan to add this directly as a figure in the manuscript?  I think it would be valuable to draw attention to these great features.  The only downside may be if we expect the front end to continue evolving such that this snapshot of the features would grow stale quickly.

We should add a paragraph about the front end features and plugins to the `Manubot` section.  Maybe after the `Manubot uses Pandoc...` paragraph?  @dhimmel or @vincerubinetti do you want to take the lead on that?

We can discuss these upgrades in response to #132 and #134.

**Comment by dhimmel** [comment]
> Do we plan to add this directly as a figure in the manuscript?

I think we should. There are two aspects that the figure shows. First, the conceptual feature (as indicated by the panel names). Second, a stylistic implementation of the concept (as shown by the figures). The specific implementation helps the viewer understand the concept. While the implementation / style may change, I think the concepts are more stable. Therefore, I view this figure as a somewhat academic exposition of what interactive features an article viewer can provide to enhance its utility.

We also may want to use this figure in the manubot documentation, but let's prepare it for the manuscript first.

### Specific panel feedback

+ TOC plugin: do we want to have the blue highlighting of the section heading, as if you had just clicked the TOC link? I know this intermixes the plugins, so still undecided whether it's good.
+ Lightbox: the scrollbar in the caption is a bit ugly. Doesn't it depend on which platform is used to render the HTML? Perhaps we could remove it for this viz?
+ Hypothesis. Would be good to show hightlights and comments (with hypothes.is panel open). https://trang1618.github.io/tpot-ds-ms/ could be a good manuscript for this because it has both. I can see if @trang1618 would like to update it to the latest frontend.
+ Jump to citation: I think an annotation box or arrow pointing to the jumper would help clarify this. Perhaps we want to pick a color for annotations that we use in all panels to clearly indicate what is not part of the manuscript but instead is an annotation. Currently, permalinks uses black which is also used by manuscripts.

**Comment by agitter** [comment]
After more consideration, I also favor using this directly in the manuscript.  The more important points about Manubot we can convey through figures alone the better.  Those appear in PubMed and other places as a summary of the full paper.

**Comment by vincerubinetti** [comment]
> * TOC plugin: do we want to have the blue highlighting of the section heading, as if you had just clicked the TOC link? I know this intermixes the plugins, so still undecided whether it's good.

Another thing is that, unlike any other feature, that "glow" (as I call it in the code) is a temporary animation just for a small visual aid. I'm not sure it'll be clear what it is doing or what it means in a static snapshot.

> * Lightbox: the scrollbar in the caption is a bit ugly. Doesn't it depend on which platform is used to render the HTML? Perhaps we could remove it for this viz?

I can take this out. Had it in to show that it will still work when the caption is long - sort of to indicate "we've thought of everything". But yeah it doesn't look super great. And yes it's platform dependent. We can take it out though because it's basic enough that it should be a given (even though so many websites don't take it into consideration). Should I take out the scrollbar in the TOC panel too?

Other two comments are :+1:, will incorp.

**Comment by vincerubinetti** [comment]
Here is my draft text. This is to be inserted after `Citation utility` and before `Authorship`. The paragraph of text in the upper-left corner of the image/figure will be removed, just leaving `o-<M>-o PLUGINS` centered in the whitespace.

```markdown
### Interactive features and appearance

Manubot comes with several "plugins" that can be included in manuscripts exported as HTML.
These plugins add special interactive functionality that enhances the user experience of viewing and reading manuscripts (@fig:plugins).
The build process can also accommodate different "themes", which change the general aesthetics and appearance of the exported document (for example, from a contemporary sans-serif style to a more traditional serif style).

![
Screenshots of the various Manubot plugins, illustrating their functionality and usefulness.
](images/plugins.png "Manubot Plugins"){#fig:plugins}

The Manubot "front-end" (layout, look, controls, behavior, etc.) is designed to be in line with current best practices and user expectations of the modern web.
In addition, the plugins utilize standard technology built in to (almost) all major web browsers, allowing them to be relatively lightweight, modular, and easy to configure.
```

**Comment by dhimmel** [comment]
> Here is my draft text

Looks great. Can you open a PR, where we'll perform the review.
