### ISSUE TITLE
Authorea corrections to writing platform table

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#195]
Alberto from Authorea reviewed our collaborative writing platform table, and we have some corrections to make.  The comments are Hypothesis annotations on this version of the manuscript: https://greenelab.github.io/meta-review/v/dd0882978b274734f4e2197f096678f644cceaca/#tbl:platforms

We can discuss any of these where we need clarification.  We should also review other parts of the text that are relevant, such as our sections on contribution tracking and citation by identifier.

**Comment by slochower** [comment]
We have "Character-level provenance for text" marked at "No" (with brief explanation). Authorea commented and said:

> Yes. There is character-level provenance as every edit is logged in the Git repository behind each article at every save event (every second).

While I have no reason absolutely no reason to cast doubt on this, if I log in to my dummy Authorea manuscript that I used to explore the features last week, and click on the "Version History" tool, I can see a handful of timestamped edits. Moving between the edits sometimes shows me entire words or phrases that I added (some of which is gibberish I was just typing to experiment). Is it possible that Authorea tracks character level provenance but this is not shown to users by default? Or maybe it requires a level of sophistication with the tools that I don't have. I am admittedly a novice Authorea user. But I would say this raises a question of what we are getting across in the table: what is technically done (or technically possible) or what a user sees. Is this distinction clear? (I think this comment would also stand for Overleaf -- an advanced user can probably user the `git` client to synchronize every commit while a web-interface-only user will probably only get certain labeled or time-stamped versions.)

![image](https://user-images.githubusercontent.com/5393995/55735627-90e04100-59d6-11e9-8957-038b140649aa.png)

**Comment by slochower** [comment]
On WYSIWYG: it seems more like Rich Text than true "what you see is what you get" to me, because if you compare the "editing mode" (my term) in the screenshot above and then export a manuscript, the manuscript subjectively *looks* different. True WYSIWYG, in my opinion, should also accurately reflect margins and line breaks, text justification, etc.

[Scientific Paper.pdf](https://github.com/greenelab/meta-review/files/3055028/Scientific.Paper.pdf)

**Comment by dhimmel** [comment]
@slochower did you set up Authorea's GitHub integration? I'd like to see the git repository to learn more about what exactly the commit history contains?

**Comment by dhimmel** [comment]
I'm copying all of Alberto's comments below for reference

### Character-level provenance for text

> **No (versions tracked by day)**
Yes. There is character-level provenance as every edit is logged in the Git repository behind each article at every save event (every second).

### Citation by identifier

> **No**
Yes, we support citation by DOI and URL and search via Crossref, Pubmed and Datacite

### Document format

> **LaTeX**
Nope, HTML. LaTeX is just a format you can include in a document. Same for Markdown and Javascript. Main document format is HTML.

### Technical expertise required

> **Yes**
I beg to differ. The majority of Authorea users today think of latex as natural rubber, not a typesetting system ;-)

### WYSIWYG mode

> **Rich text available**
Yes. Full WYSIWYG. Not rich text.

**Comment by dhimmel** [comment]
> it seems more like Rich Text than true "what you see is what you get" to me, because if you compare the "editing mode" (my term) in the screenshot above and then export a manuscript, the manuscript subjectively looks different.

I think we may be getting mixed up based on which format the article is viewed as. @apepe indicates the main output format is HTML, which I believe you can create for your manuscript under the "share" button. I don't see a way to download the rendered HTML, but you can use the Authorea hosted HTML. It seems that the HTML output may actually be WYSIWIG to the online GUI editor?

The PDF output is not WYSIWIG, but I think @apepe is saying that PDF is not the primary output. I believe the PDF is created by way of LaTeX, which could be where our confusion regarding the "document format" is occurring. When I download an article to a zip file, I see that the content is stored as HTML. So I am guessing the editor is a way of directly editing HTML. Perhaps also causing confusion is that the bibliographic metadata is specified as `.bib` records. However, I don't think LaTeX is being used to render them, but probably a javascript package instead?

**Comment by agitter** [comment]
I also [asked](https://twitter.com/anthonygitter/status/1115217922513887234) a follow up question:
> Is there a reference for how git commits are created in the Authorea repo? What happens if two authors simultaneously edit in between the every-second save events?

This is a problem on Overleaf as far as I can tell.

**Comment by slochower** [comment]
> @slochower did you set up Authorea's GitHub integration? I'd like to see the git repository to learn more about what exactly the commit history contains?

I did click "Setup GitHub integration automatically" but I'm not sure what it did! I authorized Authorea for my GitHub account, but it didn't ask me to create a new repository or anything. I didn't have time to further play around with this. I assume if you go through the manual setup process you have more options (I can see that it asks for repository name and branch). So this part is pretty opaque to me so far.

Edit: Ohhhhhkay. It automatically created a new repository called "Scientific-Paper". https://github.com/slochower/Scientific-Paper 

The commits look fairly self-explanatory, but there are various cryptic HTML and TeX files in the repository, too.

> I think we may be getting mixed up based on which format the article is viewed as. @apepe indicates the main output format is HTML, which I believe you can create for your manuscript under the "share" button. I don't see a way to download the rendered HTML, but you can use the Authorea hosted HTML. It seems that the HTML output may actually be WYSIWIG to the online GUI editor?

That's a good insight. I was not thinking that HTML is the main output format.

**Comment by dhimmel** [comment]
@slochower can you add me as a collaborator on the Authorea manuscript via the share button? I would like to make some changes via the web UI and see how they translate into git commits.

**Comment by slochower** [comment]
@dhimmel done via gmail.

**Comment by dhimmel** [comment]
Okay I made some edits and I do see very granular commits (like on an every second basis). See https://github.com/slochower/Scientific-Paper/commit/01f3e4ba43ef8d4e1750a4ace31488b26a098e0a. Authorea does set the commit author properly. I would say the big difference with Manubot is that the usefulness of commits is diminished when the commits when they are not intentional sets of changes but instead sequences of keystrokes.

**Comment by slochower** [comment]
Agree. And also not knowing that the file `pfp675ptdg.md` corresponds to your `#Markdown section`, especially without a meaningful commit message.

**Comment by dhimmel** [comment]
> Agree. And also not knowing that the file pfp675ptdg.md corresponds to your #Markdown section, especially without a meaningful commit message.

Yeah. I think you could rename sections and edit [`layout.md`](https://raw.githubusercontent.com/slochower/Scientific-Paper/master/layout.md) to get a more human readable section nomenclature. But I agree that in general, directly editing the git source to update an Authorea manuscript would be difficult. Also what happens if you mess up the syntax, can you see build error messages somewhere?

**Comment by slochower** [comment]
> But I agree that in general, directly editing the git source to update an Authorea manuscript would be difficult.

Right. I'm not sure if Authorea has the ability to pull from GitHub and/or deal with merge conflicts.

**Comment by slochower** [comment]
> For example, the file layout.md is crucial as it instructs Authorea what files to render. If you delete it, the Authorea article will break! In order to build your article locally when working offline we suggest to use this Python Script by our fellow Erik Tollerud.

From: https://support.authorea.com/en-us/article/syncing-articles-to-github-zubain/

**Comment by apepe** [comment]
Hey friends, sounds like you figured out the answers to all the questions you had :) To sum up: every article is a Git repo. Main article format is html. `layout.md` lists what files in the repo are rendered in the document view. It can contain file formats such as latex, md, html, js, figures, tables, jupyter notebooks. Every save event (which happens every second) creates a Git commit so this is VERY granular (too granular indeed). Git integration allows you to push and pull to your Authorea document via Git. In the Authorea web interface multiple authors can write at the same time BUT we lock paragraphs to avoid conflicts. If a conflict arises due to someone pushing and pulling via Git and someone writnig on the web, we generate a `failsafe` branch and the conflict needs to be solved and merged manually by the article owner. We do use pdflatex/pandoc to generate PDFs and Word exports.
