### ISSUE TITLE
Figure 2 cut off in PDF

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#202]
The right side of Figure 2, the deep review contributions plot, is truncated in the current PDF.

@vincerubinetti @dhimmel any ideas as to what could be causing this?

**Comment by dhimmel** [comment]
Ah yes [see here](https://greenelab.github.io/meta-review/v/5b23bdb102a938026b6ed25181bc5ac73e5f21e9/manuscript.pdf#page=8):

> ![image](https://user-images.githubusercontent.com/1117703/55876961-d0d62e00-5b66-11e9-9e99-e3e0032b228b.png)

**Comment by vincerubinetti** [comment]
@agitter Does it happen when you print the html version in Chrome (`ctrl+p` and look at the print preview)? For me, in the [latest deployed version of the manuscript](https://greenelab.github.io/meta-review), doing a print preview looks fine, which suggests that it's WeasyPrint's fault.

Also, can you try removing the `.white` background class from the image and see if the problem still occurs?

I'll look into it more to see if I can troubleshoot the issue.

**Comment by dhimmel** [comment]
@vincerubinetti and I looked into this locally and we see that the clipping occurs in WeasyPrint, with or without specifying `.white`. WeasyPrint also appears to have an issue when we don't specify `width="100%"` making the figure minuscule in the PDF.

It's possible that WeasyPrint has fixed some of these issues but I think we're pinned to an old version due to a conda dependency trap.

We've been talking about trying out athenapdf in https://github.com/manubot/rootstock/issues/170. So perhaps this is a good time to prototype it on a non-rootstock repo.
