### ISSUE TITLE
PLOS formatting requests

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#226]
The PLOS Computational Biology team emailed the following message about formatting.  The attachment below contains the specific requests.  I'll create individual issues for each request and use this as the meta issue, as during revision.
- [x] Metadata verification #229
- [x] Provide a .doc or .docx version of your manuscript file.
- [x] Numeric affiliations #230
- [x] Author summary paragraphs #231
- [x] Remove figures from text #232
- [x] Reference format #233
- [x] Figure formatting #234
- [x] Striking image #235

Should I contact them to ask about all of the links in our text?  If they remove them during proofing without telling us, the text will suffer.

> This is the FINAL stage for you to copyedit your manuscript and figure files. We strongly recommend that all authors double check ALL files prior to the final versions being submitted. The version submitted at this stage will be posted online ahead of the final version, unless you have already indicated that you do not wish to post an early version. Changes to the manuscript, statements, author list, references, equations, or figures (including resizing) at the proof stage WILL NOT BE ACCEPTED 

> Thank you for your patience while we evaluated your manuscript, 'Open collaborative writing with Manubot', to ensure it meets our formatting requirements prior to publication. 

> We require you to make some technical changes to your manuscript, which are listed in the attached document. Your manuscript will not proceed to production until you have satisfactorily completed these requests.

> To access your manuscript and complete these changes, please follow this link `<redacted>`. You will find the submission in "Current Task Assignments", and will need to click "Submit Task" in order to upload your corrected file(s).

> Please note, once these technical changes have been completed the corresponding author will receive a typeset proof for review, to ensure errors have not been introduced during production. Additional changes WILL NOT be accommodated at the proof stage and a correction notice will need to be issued after publication if a further change is required and appropriate. 

> It is strongly recommended that ALL authors now check the manuscript and figures, as well as author-provided statements including:
> *	The author list, contributions, and affiliations
> *	Data availability 
> *	Funding
> *	Conflicts of interest

> These statements are also provided for review in the attached document with the required technical changes to your document. This is the FINAL opportunity to make changes to your manuscript, so please do check ALL files thoroughly.

> If you have any questions about these requests, please do get in contact. 

Instructions in the submission system:

> To access the current files associated with your submission, please go to 'Assignment Files'. Once you have addressed the requests outlined in the Assignment Letter, please click "Submit Task". This will open a new window where you can upload your corrected file(s), including the tracked-changes version of your manuscript file. You can confirm any necessary details, including funding, competing interests, and data availability, by inserting comments in the email template generated at the bottom of the window - please add your details after "Author Comments:". Please do not remove any text from the template. Click "Submit Production Task" once you have completed the process, and we will review the changes you have made. We will notify you of any additional requests, if required, before passing your submission through to production.

Attachment: [pcbi.1007128.docx](https://github.com/greenelab/meta-review/files/3242696/pcbi.1007128.docx)

**Comment by dhimmel** [comment]
I've converted the DOCX to markdown pasted below, courtesy of:

```
pandoc --to=gfm --wrap=none pcbi.1007128.docx
```

<details>
<summary>Expand to see DOCX contents</summary>

# For: "Open collaborative writing with Manubot"

> To access your manuscript and complete these changes, please follow the link in the email we sent you. You will find the submission in "Current Task Assignments", and will need to click "Submit Task" in order to upload your corrected file(s).
> 
> **This is the FINAL stage for you to copyedit your manuscript and figure files.** We strongly recommend that all authors double check ALL files prior to the final versions being submitted. Changes to the manuscript, statements, author list, references, equations, or figures, including resizing, at the proof stage WILL NOT BE ACCEPTED.
> 
> **Questions?** Email ploscompbiol@plos.org quoting your manuscript number.

# METADATA CHECK

Please confirm that the following information is correct and contact us if any changes are necessary. This information will be indexed in PubMed and published by *PLOS Computational Biology* as you have written them.

  - Your **Author Contributions** will be typeset as follows:



  - Conceptualization: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter

  - Data curation: D.S. Himmelstein, A. Gitter

  - Formal analysis:

  - Funding acquisition: D.S. Himmelstein, C.S. Greene

  - Investigation: D.S. Himmelstein, D.R. Slochower, A. Gitter

  - Methodology: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter

  - Project administration: D.S. Himmelstein, C.S. Greene, A. Gitter

  - Resources: C.S. Greene

  - Software: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, D. Hu, V.S. Malladi, A. Gitter

  - Supervision: D.S. Himmelstein, C.S. Greene, A. Gitter

  - Validation: D.S. Himmelstein, V.S. Malladi, A. Gitter

  - Visualization: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter

  - Writing original draft: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter

  - Writing review & editing: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, V.S. Malladi, C.S. Greene, A. Gitter



  - An **Early Version** of your manuscript:
    
      - WILL be published online ahead of the final version

> If you (or your institution) are planning a press release for this article, please contact us as soon as possible to ensure that an early version of your paper is not published.

  - Your **financial disclosure** will be typeset as follows:

DSH, DH, VR, and CSG were supported by Grant G-2018-11163 from the Alfred P. Sloan Foundation and Grant GBMF4552 from the Gordon and Betty Moore Foundation. VSM was supported by Grant RP150596 from the Cancer Prevention and Research Institute of Texas. The funders had no role in study design, data collection and analysis, decision to publish, or preparation of the manuscript.

  - Your **competing interests** statement will be typeset as follows:

The authors have declared that no competing interests exist.

  - Your **data availability statement** will be typeset as follows:

The source code and data for this manuscript are available at https://github.com/greenelab/meta-review and archived via Software Heritage identifier swh:1:dir:5e644c3a487081b272b2c9b52bcd55caa89c4f85. Source code for Manubot resides in the following repositories: https://github.com/manubot/manubot (GitLab mirror (https://gitlab.com/manubot/manubot) archived at swh:1:dir:1eb3b7e6d7e21239fedccf25a186af622ee6912e, packaged on PyPI (https://pypi.org/project/manubot/)), and https://github.com/manubot/rootstock (GitLab mirror (https://gitlab.com/manubot/rootstock), archived at swh:1:dir:cfc3af2e8e1a0d9b639fdab0943731e608910731).

  - The details of the **corresponding author** will be typeset as follows:
    
      - Name Daniel S. Himmelstein, Anthony Gitter
    
      - E-mail <daniel.himmelstein@gmail.com> (DSH); <gitter@biostat.wisc.edu> (AG)
    
      - ORCiD 0000-0002-3012-7446, 0000-0002-5324-9833

  - Please check the **authorship and affiliations** list on the title page of your manuscript. These details will be used to index the authorship of your manuscript and therefore should be checked carefully for any errors.

  - Please ensure that if you have any protocols associated with [<span class="underline">protocols.io</span>](https://www.protocols.io/) in your manuscript, they are made public before publication to guarantee immediate access to the methodological details.

  - Your **title** will be typeset from the submission system, not the manuscript file. Please check that the following is correct:

Open collaborative writing with Manubot

  - Your **short title** will be typeset from the submission system, not the manuscript file. Please check that the following is correct:

Open collaborative writing with Manubot

Please note that if you wish any word to be **italicised**, this will need to be manually changed in the Editorial Manager system. Please contact the journal office to address this.

# MANUSCRIPT REQUIREMENTS

Please update the locked-track-change version of your manuscript we have provided with the following changes:

\-Please provide a .doc or .docx version of your manuscript file.

\-Please modify the Affiliations section of your manuscript so that all affiliations listed contain a Department, Institution, City, and Country, and that affiliations are ordered in ascending numerical order. To see a typical title page with formatted affiliations, please see <http://journals.plos.org/plosgenetics/s/file?id=RSNU/PLOSGenetics_formatting_sample_title_authors_affiliations.pdf>.

\-Please modify the formatting of your Author Summary so that it is not broken into multiple paragraphs.

\-Your figures are currently included within your article file. Please remove them from your article file and upload them as separate figure files. At this time, we can only accept figures under 10 MB each in .TIF (preferred) and .EPS format. For additional details, please see our figure guidelines: http://journals.plos.org/ploscompbiol/s/figures. Additionally, please ensure that you have included a corresponding caption/legend in the manuscript file.

\-Your references need to be formatted according to the PLOS style. PLOS uses the numbered citation (citation-sequence) method and first six authors, et al. Authors should be listed as "Last name, First Initial". If using EndNote, please use the following style file: https://endnote.com/style\_download/plos-public-library-of-science-all-journals/

# FIGURE REQUIREMENTS

PLOS offers a figure-checking tool, PACE ([**<span class="underline">https://pacev2.apexcovantage.com</span>**](https://pacev2.apexcovantage.com/)), to help authors to ensure all figures meet PLOS requirements so that the quality of published figures is as high as possible. **Please use this tool to help you address the requests below.**

PACE is a digital diagnostic and conversion tool for figure files. It will provide information about any failed check(s) and, if able, will automatically convert the figure file into an acceptable file that passes quality checks. PACE requires you to register for an account to ensure your figure files are processed securely.

Please complete the following instructions regarding your figure files:

\-Figure 1 has been modified to meet with formatting requirements. Please review the revised figure to ensure that it meets with your approval. Please note that if you approve of this revised figure, you do not need to upload it to the system.  
  
\-Figure 2 is acceptable for publication.  
  
\-Figure 3 exceeds the dimension limits for Figures. Figures must be less than 19.05cm in width, and less than 22.225cm in height. Please note that figures will be typeset at the dimensions provided. Please make the necessary adjustments and re-upload your Figures.  
In Photoshop: Image→Image Size. Make sure the Resample Image checkbox is NOT checked. If the Width is over 19.05cm, type 19.05 in the Width box (19.05cm is our maximum allowable width for figures).  
In GIMP: Image→Scale Image. Set the units of measurement, in the pull down menu next to Height, to millimeters. If the Width is over 190.5mm, type 190.5 in the Width box (19.05cm is our maximum allowable width for figures) and hit Tab. The new Height of the figure will appear, scaled proportionately to the change in Width.  
  
\-Figure 3 looks like it was originally at a lower resolution and will appear blurry or pixelated if published. Text and images should appear crisp and clear. Please note that this problem will not be detected or corrected by the PACE tool, and this will not be fixed by simply increasing the resolution of your Figures in the image editing software. Please carefully review the PLoS Figure Guidelines and provide Figure files that were originally created at 300 pixels/inch (dpi) and at least 6.68cm wide, but less than 19.05cm and under 22.225cm tall. For further information, please see the Figure Guidelines (<http://journals.plos.org/ploscompbiol/s/figures>).  
  
1\) Export a PDF from PowerPoint/Word/Excel (or other image source file). On a Mac, click on the 'PDF' button in the printer dialog box and select 'Save as PDF'. On a PC, send the file to print and select 'Adobe PDF' or 'PDFCreator' (it's freeware) from your list of available printers.  
If you are using Adobe PDF, then go to Printer Properties, Default Settings and select Press Quality.  
If you are using PDFCreator, Go to 'Printer Properties' and then click on 'Advanced' on the bottom right. Under 'Graphic', go to 'Print Quality' and select 600dpi.  
2\) PHOTOSHOP: When you open up the PDF, make sure that the 'Constrain Proportions' box is checked. Set the 'Resolution' to 300dpi (118.11 pixels/cm) and set the 'Bit Depth' to 8 bit. Use the crop tool (next to the eyedropper) to remove unnecessary white space. Go to - Image - Image Size. Make sure the 'Constrain Proportions' and 'Resample Image” boxes are checked.  
To ensure that your Figures publish properly, please delete the alpha channels from each Figure file. In Photoshop, select it in the Channels Palette and click on the trash can icon. When you save the TIFFs make sure that the 'LZW' button is checked and 'Discard Layers and Save a Copy' button is checked.  
3\) GIMP: When you open up the PDF, set the resolution to 300. Make sure the chain link icon is joined together. Then change the size of your figure according to the pixel specifications mentioned in step 2) above. To ensure that your Figures publish properly, please delete the alpha channels from each Figure file. In GIMP, go to Layers - Transparency - Remove Alpha Channel. When you are done, 'SAVE AS' (or Export if GIMP 2.8). Select File Type - 1st TIFF option. Make sure to use LZW compression.  
4\) Print out your figures on a desktop printer. Text and graphics should appear clear and crisp with no pixelated or blurred edges.  
5\) If the resulting figures are still blurry, then your original source images are too low of a resolution. Please increase the resolution of your original source images, and repeat this process.  
  
\-Please resave your Figure 3 using LZW compression (loss-less) in order to reduce the file size by over 75% and re-upload.  
In Photoshop: File→Save As. Save as TIFF, Image Compression set to LZW, Pixel Order set to Interleaved, Byte Order set to IBM PC.  
In GIMP: File→Save As. Click the + sign next to Select File Type (By Extension). From the menu that appears, select TIFF. Click Save. Set Compression to LZW. If you're prompted about layers in the file, select Flatten Image.

Please note that this is your only chance to adjust figures, changes to figures (including resizing) at proof will not be accepted.

You can also be able to upload a Striking Image to accompany your article if one is available. If this image is judged to be suitable, it may be featured on our website. Images should be high resolution, eye-catching, single panel images. If your image is from someone other than yourself, please ensure that the artist has read and agreed to the terms and conditions of the Creative Commons Attribution License. Note: we cannot publish copyrighted images.

</details>

**Comment by agitter** [comment]
Thanks for converting @dhimmel.  I'll stop copying from the detailed instructions in the individual issues now that we have everything here.

**Comment by dhimmel** [comment]
I'm thinking about which issues potentially affect the manuscript on GitHub and which issues can be handled without any changes to this repo. Here are the issues that I think it may make sense to modify the git repository while addressing them:

- [ ] https://github.com/greenelab/meta-review/issues/231
- [ ] https://github.com/greenelab/meta-review/issues/230
- [ ] https://github.com/greenelab/meta-review/issues/233
- [ ] https://github.com/greenelab/meta-review/issues/234

Is it so that all changes we make at this point should be directly to the word document from our previous submission? Or should we export another DOCX and then create a diff later? I'm leaning towards the former. For some issues, like the references formating, we can regenerate the bibliography with Manubot and copy-and-paste the revised section into the existing DOCX with tracked changes?

Finally, we can make changes to the Manubot source, that we end up reverting after producing a suitable output. This would make sense for changes where the journal requirements are a downgrade from our current implementation, e.g. https://github.com/greenelab/meta-review/issues/231 and https://github.com/greenelab/meta-review/issues/233.

**Comment by agitter** [comment]
For the last submission, I only uploaded the manuscript and diff as PDFs.  Because PLOS doesn't have a DOCX of our manuscript, I expect we could safely export another DOCX and create a diff later.  They'll use the new DOCX as the master version of our manuscript.

Could we make any final commits that we want to keep in the HTML version, bundle those with the [post-submission commits](https://github.com/greenelab/meta-review/compare/v3.1...master), and tag that?  Then we make any other edits needed for the resubmission and revert back to the tagged version once we pass the proofing stage.  Maybe that's what you are suggested by your comment above about reverting changes that are a downgrade.

**Comment by slochower** [comment]
Please feel free to tag me in the relevant sub-issues.

**Comment by vsmalladi** [comment]
Let me know how I can help.

**Comment by dhimmel** [comment]
> Maybe that's what you are suggested by your comment above about reverting changes that are a downgrade.

I think we can make changes that are just-for-submission and general changes, as long as they aren't intermixed in the same pull requests. Then we'll tag the version we use to derive the resubmission DOCX. Then if we want to undo some of the just-for-submission changes, we can do a `git revert` and look through the commit history.

**Comment by agitter** [comment]
@dhimmel that sounds good to me.  You can go ahead and merge the other PRs I approved.

**Comment by agitter** [comment]
@dhimmel it looks like we are getting pretty close to finishing the formatting changes.  Once we resolve the remaining reference formatting issues in https://github.com/greenelab/meta-review/pull/241 (or rather those that we want to address), we should be able to quickly finish everything and resubmit.

**Comment by agitter** [comment]
I believe we are ready to resubmit after merging #242 and #243.

It's not clear to me whether we need to generate another diff for this submission.  The submission system states

> This will open a new window where you can upload your corrected file(s), including the tracked-changes version of your manuscript file. 

But perhaps that assumes we already submitted a DOCX version previously?  I plan to submit without a diff and generate one later if they need it.  I will start with the final https://github.com/greenelab/meta-review/blob/output/manuscript.docx and make the manual changes from there.  The manual changes are:
- Delete figures
- Format the _Paywall_ movie reference

**Comment by dhimmel** [comment]
@agitter great. I'll be available for the next couple hours but then will go offline for 5 days. So hopefully you will be able to move forward with the resubmission!

**Comment by agitter** [comment]
@dhimmel I'm starting the submission process.  If I need to make any minor changes at the last minute, I may self-approve the PR so that we don't have to wait for you to return.

**Comment by dhimmel** [comment]
> If I need to make any minor changes at the last minute, I may self-approve the PR so that we don't have to wait for you to return.

Yes please do!

**Comment by agitter** [comment]
I resubmitted with the formatting changes: https://github.com/greenelab/meta-review/releases/tag/v4.0
