### ISSUE TITLE
Templating quantitative values

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#23]
Certain numbers should be calculated and inserted into the manuscript via template. This will provide a proof of concept use for our templating and end-to-end reproducibility claims. In addition, it will make the manuscript easier to maintain as the numbers change.

@agitter do you want to list all the metrics you'd like me to calculate? Some thoughts are:

+ number of deep review contributors
+ number of deep review commits
+ number of accepted deep review pull requests

**Comment by agitter** [comment]
The stats I find most interesting are:
- number of authors from `authors.tsv`
- number of contributors who made their first contribution after May 28, 2017

Also interesting:
- number of deep review commits
- number of accepted deep review pull requests.

Do you think contributors is better than authors?  I was thinking we'd have the author count be consistent with the latest version of paper on bioRxiv.  The number of commits to master underestimates the total commits because we squashed commits during the most extensive editing period.

The number of institutions would take more work to template because we have some institutions represented multiple times with different departments.
