### ISSUE TITLE
Smart Papers: Dynamic Publications on the Blockchain

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#95]
https://doi.org/10.1007/978-3-319-93417-4_20

> Distributed Ledgers (DLs), also known as blockchains, provide decentralised, tamper-free registries of transactions among partners that distrust each other. For the scientific community, DLs have been proposed to decentralise and make more transparent each step of the scientific workflow. For the particular case of dissemination and peer-reviewing, DLs can provide the cornerstone to realise open decentralised publishing systems where social interactions between peers are tamper-free, enabling trustworthy computation of bibliometrics. In this paper, we propose the use of DL-backed smart contracts to track a subset of social interactions for scholarly publications in a decentralised and reliable way, yielding Smart Papers. We show how our Smart Papers approach complements current models for decentralised publishing, and analyse cost implications.

This could be relevant for our next round of revisions.  They have a paragraph about Manubot in the related work section.

**Comment by dhimmel** [comment]
Here's the section where they mention Manubot:

> the best of our knowledge, the open-source system that comes closest to ours is Manubot2, a tool for writing scholarly manuscripts via GitHub. Manubot automates citations and references, versions manuscripts using git, and enables collaborative writing via GitHub. Data from Git related to commitment and authorship can be used to establish attribution. An innovation introduced by Manubot’s authors3 is the timestamping of manuscript versions on the Bitcoin blockchain, to prove the existence of the manuscript at a given point of time in a decentralised way. Our approach generalises Manubot’s idea to further social interactions around publications.

The idea is that all interactions involved in publishing should be verifiable and immutable.

However, I'm not sure whether their proposal is directly applicable to the Manubot. From my understanding, they are proposing to perform the interactions involved in publishing on the Ethereum blockchain. For example, peer review would be recorded on the blockchain. "Smart Papers" is not a very good term for this ("smart contracts" is not a very good term for Ethereum contracts anyways). I'd say it's more like blockchain-tracked publishing. I guess you could say it generalized our timestamping to the interactions in scholarly publishing.

However, it wasn't clear to me whether they have actually implemented this idea. Also, perhaps the Steem blockchain would be more appropriate for scholarly publishing, since it could directly host the textual content without a per-transaction fee. I'm going to close this issue. Given that blockchain papers can be time consuming to understand, it's probably ideal to focus our citations on projects that have existing implementations running in the wild.

**Comment by agitter** [comment]
Fine with me.  Thanks for looking it over.
